### ISSUE TITLE
merging to upstream

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/crunch#1]
See:
- https://github.com/BinomialLLC/crunch/pull/12
- https://github.com/BinomialLLC/crunch/pull/13

Once these two PR get merged, we can drop this fork.

**Comment by DolceTriade** [comment]
yay

**Comment by illwieckz** [comment]
Note that when we were used to do `crunch -renormalize` with our own crunch fork, the patched upstream would require to do `crunch -renormalize -rtopmip` instead because that extra behavior was default in our version but will not be in upstream.

**Comment by illwieckz** [comment]
See also:

- BinomialLLC/crunch#14

By the way I did not get any answer from upstream yet.

**Comment by DolceTriade** [comment]
boo

**Comment by illwieckz** [comment]
It looks like Unity is maintaining crunch (they added more than 50 commits above @BinomialLLC's history) so I replayed the PR on Unity side:

- Unity-Technologies/crunch#2
- Unity-Technologies/crunch#3
- Unity-Technologies/crunch#4

**Comment by DolceTriade** [comment]
yay

**Comment by illwieckz** [comment]
Still waiting for an answer from Unity's side…

**Comment by DolceTriade** [comment]
boo

**Comment by illwieckz** [comment]
issue moved there: DaemonEngine/crunch#2
